# generated using:
# code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.project-manager
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension BazelBuild.vscode-bazel
code --install-extension burkeholland.simple-react-snippets
code --install-extension bwildeman.tabulous
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension dotiful.dotfiles-syntax-highlighting
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension ericadamski.carbon-now-sh
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.terminal
code --install-extension foxundermoon.shell-format
code --install-extension garytyler.darcula-pycharm
code --install-extension GitLab.gitlab-workflow
code --install-extension Gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension James-Yu.latex-workshop
code --install-extension jasonnutter.search-node-modules
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension KevinRose.vsc-python-indent
code --install-extension letmaik.git-tree-compare
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension magicstack.MagicPython
code --install-extension mdickin.markdown-shortcuts
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.gitignore
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oderwat.indent-rainbow
code --install-extension peakchen90.open-html-in-browser
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension slevesque.vscode-zipexplorer
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension TabNine.tabnine-vscode
code --install-extension TrungNgo.autoflake
code --install-extension Tyriar.terminal-tabs
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension Vtrois.gitmoji-vscode
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension yamajyn.commandlist
code --install-extension Zignd.html-css-class-completion
code --install-extension ziyasal.vscode-open-in-github
